### ISSUE TITLE
CSS bug, CFR history tab

### ISSUE THREAD

**Issue by cmc333333** [18F/eregs-platform#39] opened 2016-07-25 17:16 UTC
Looks like the heading is being covered by the timeline info when scrolling:

<img width="239" alt="screen shot 2016-07-25 at 1 15 14 pm" src="https://cloud.githubusercontent.com/assets/326918/17110234/fb29c26a-5269-11e6-91c1-2436ea2703bc.png">

**Comment by jehlers** [comment] 2016-09-30 18:34
This is a duplicate of #56

**Closed as completed by jehlers** 2016-09-30 18:34 UTC
